### ISSUE TITLE
Misclassification of java interoperability as function

### ISSUE THREAD

**Issue by wardle** [NoahTheDuke/splint#2]
When mapping using an anonymous fn to use java interop, splint says 'No need to wrap function. Clojure supports first-class functions', but you generally cannot unwrap in this case. e.g. `(map #(Integer/parseInt %) ["1" "2" "3"])`

PS. Thank you very much for this linter - really brilliant at identifying style improvements - particularly those where I can vastly simplify code such as preferring `or` etc.  Thank you!

**Comment by wardle** [comment]
The only method I could think of to do this without running code, and only using structure, would be to look either for `(.` - which is obviously interop, or `([A-Z]` ie a call to a static method on a class so will be capitalised.

**Comment by wardle** [comment]
Thanks @NoahTheDuke  - I'll have a look - will be interesting!

**Comment by NoahTheDuke** [comment]
I've written a bunch of documentation about how the pattern DSL and rules objects are built, if you're still interested.

**Comment by wardle** [comment]
I'll have a look. Thanks!

**Comment by wardle** [comment]
I looked at this but it is tricky. The rough heuristic above with a dot might work for some cases, but it doesn't catch the use of static methods on a Java class.

**Comment by NoahTheDuke** [comment]
Yeah, that's definitely an issue. Without deeper analysis (like clj-kondo does), I suspect there's not much we can do.

Maybe we could use the list of built-in classes that Clojure recognizes and extract the `:use` symbols and check against those? That would cover the majority of cases I expect. That'll be a lot harder than a simple check against capital letters tho.
