### ISSUE TITLE
Certain assert expected-actual order not triggering style/is-eq-order lint

### ISSUE THREAD

**Issue by tjcampanella** [NoahTheDuke/splint#25]
This specific type of assert does not trigger the lint that checks the order of the expected and actual values. 

The lint in question is style/is-eq-order.

`(is (= (:status result) "completed"))`

It does however work if you do it like so:

`(is (= result "completed"))`

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Closed in 0b41738e404c309f79a0bf7904995ae5fdabbcd5
