### ISSUE TITLE
Ability to dump configuration

### ISSUE THREAD

**Issue by dpassen** [NoahTheDuke/splint#4]
It would be helpful, when debugging, to have an option to print out the configuration used. After the merge of `.splint.edn` file, CLI args, default values, etc.

Slack thread with some context:
https://clojurians.slack.com/archives/C04SCGV2ATX/p1683391198314179

**Comment by NoahTheDuke** [comment]
This has been added as of v1.4.0! `--config local` will print just the contents of your locally loaded `.splint.edn`, `--config full` will print everything merged together, and `--config diff` will only print where the two are different (for cases where you deliberately set the local config equal to the default).

**Comment by dpassen** [comment]
Wonderful! Thank you
