### ISSUE TITLE
Auto-fix found problems

### ISSUE THREAD

**Issue by SmetDenis** [NoahTheDuke/splint#7]
Good afternoon, @NoahTheDuke 

First of all I want to say thank you so much for your hard work!
I came here by chance through a link from kibit (I guess it was your project too).

In `kibit` I really liked the possibility of automatic replacement with the `--replace` flag.

Can you tell me if you plan to add this feature to `splint`?

Thank you in advance.

PS Maybe I didn't read the documentation well.

**Comment by NoahTheDuke** [comment]
Thanks for the kind words!

You didn't miss anything, Splint currently doesn't have any sort of replacement capabilities. I've experimented with adding them in the past but was dissatisfied by the results. Maybe now's a good time to try again.

**Comment by SmetDenis** [comment]
Thank you. I'll look forward to any experiments you may have.
Replacing it all manually is a big hassle :)
